### ISSUE TITLE
PlayerManager is private

### ISSUE THREAD

**Issue by jammehcow** [ArsenArsen/lavaplayerbridge#5]
I honestly have no idea how this implementation is used, but the example provided in the readme doesn't work at all. PlayerManager is package private so it isn't able to be used. Mistake?

**Comment by ArsenArsen** [comment]
You're correct.... Im mistaken In the README. It is `PlayerManager.getPlayerManager(LibraryFactory.getLibrary(client/jda)) `. Thanks for pointing that out.
